# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180407_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='filename',
            field=models.CharField(default='abhsid', max_length=255),
            preserve_default=False,
        ),
    ]
